### ISSUE TITLE
553 Could not create file.

### ISSUE THREAD

**Issue by rakesh050791** [xing/paperclip-storage-ftp#19]
Hi All

I am trying to upload a file using paperclip-storage-ftp, but i am getting this error every time i try to upload. I couldn't find where the problem lies. Can anyone help me?

Here is my Code for model

    require "paperclip/storage/ftp"

    class Attachment < ActiveRecord::Base
      attr_accessible :attachable_id, :attachable_type,:document
   
     has_attached_file :document,  
    :storage => :ftp,
    :path => "path",
    :url => "Url",
    :ftp_servers => [
      {
      :host => "host name",
      :user => "Username",
      :password => "Pass"
      }
    ],
    :ftp_connect_timeout => 5, 
    :ftp_ignore_failing_connections => true    
    validates_attachment_content_type :document, :content_type => %w(application/pdf)   
    end

Any suggestions would be appreciated.

Thanks

**Comment by boosty** [comment]
Will close this for now. If someone is still seeing this error, please reopen.
