### ISSUE TITLE
How to rename files?

### ISSUE THREAD

**Issue by ginolon** [xing/paperclip-storage-ftp#28]
If I use this code in my model class:

````
def rename_myfile
    if self.rename.present?
      path = self.myfile.path
      FileUtils.move(myfile.path, File.join(File.dirname(myfile.path), self.rename))
      self.myfile_file_name = self.rename
    end
  end
````

I have an error:

No such file or directory @ sys_fail2 - (/myfiles/19/original/myfileOriginalName.jpg, /myfiles/19/original/myfileRenamedName.jpg)

How to enter in ftp with FileUtils.move???

Create and Delete are working very well!

**Comment by boosty** [comment]
Hi @ginolon, 

I am not sure what you are trying to accomplish. Do you want to rename a new file *before* uploading it to the ftp servers, or do you want to rename *existing* files on all ftp servers?

**Comment by ginolon** [comment]
Both.

Let's say I have a _form.html.erb of my model. I have a text_field "rename" and I use it to rename my attachment file.

Also if I use the same form to upload, if there is something in the field "rename" I want to rename file, in this case BEFORE upload.

Everything works very well in local, but I don't know how to accomplish this in ftp.

In local I use this code:

def rename_myfile
    if self.rename.present?
      path = self.myfile.path
      FileUtils.move(myfile.path, File.join(File.dirname(myfile.path), self.rename))
      self.myfile_file_name = self.rename
    end
  end

**Comment by ginolon** [comment]
It' incredible hard to fix this problem. I know...
Also with carrierwave I have a similar problem.

**Comment by boosty** [comment]
Hi @ginolon,

I thought about this for a bit, and I think the right level to address this in in the paperclip gem, not in a specific paperclip storage backend gem like this. This way you could rename files in paperclip no matter what storage backend you use (could be S3, the local filesystem, ftp, etc.).

As far as I have seen, there is no support for renaming files in the paperclip gem today. But I think it could be done, by changing the corresponding filename values in the db and essentially copying the files to the new location and then removing the old files (utilising the existing `copy_to_local_file`, `flush_writes` and `flush_deletes` methods which every paperclip storage backend supports).

That being said, I am closing this issue and hope you can take this idea to the paperclip guys.
