### ISSUE TITLE
How to reproduce same interpolation as Paperclip default?

### ISSUE THREAD

**Issue by arisxama** [xing/paperclip-storage-ftp#30]
I'm trying to change from default Paperclip storage to ftp so i can have all assets in a seperate server. The thing is that i cannot reproduce paperclip's default "id_partition" naming so i can make it work with my old data.

Any ideas?

**Comment by arisxama** [comment]
I think i figured how it. Paperclip default is something like .../:id_partition/:style/:filename corresponding to .../000/000/130/small/image.jpg 
hope it helps someone.

**Comment by boosty** [comment]
Ok, I'll close this as a non-issue :wink:
