### ISSUE TITLE
How to delete local files after uploading them ?

### ISSUE THREAD

**Issue by nyddogghr** [xing/paperclip-storage-ftp#33]
Hi,
I would like to know if there was a way to delete a file after it has been uploaded on an ftp server ?
Currently I create my object with an attachment, and the file is downloaded on the server before uploading it on the ftp. But it seems it stays in the tmp folder of my rails app.

Thanks

**Comment by boosty** [comment]
Hi @nyddogghr, 
this gem does not really manage your local files in any way. You should remove the file yourself after the ftp upload is done.

**Comment by nyddogghr** [comment]
OK, thanks for you answer.
