### ISSUE TITLE
550 No files found.

### ISSUE THREAD

**Issue by cbagnoli** [xing/paperclip-storage-ftp#36]
Hi All.

I'm trying to upload a pdf from my PC to a remote server using paperclip-storage-ftp.
The form load the file to the /tmp directory on my local server.
The gem create a new directory on the remote server, but it seems unable to send the file.
And I got the error "550 No files found.".
I'm able to do it by hand.

Here is my Code for model:
-----------------------------------
  has_attached_file :pdf, {
    :storage => :ftp,
    :path => "/srv/www/rails/sistema/public/system/:class/:attachment/:id_partition/:style/:filename",
    :url => "http://sistema.dominio.com.ve/public/system/:class/:attachment/:id_partition/:style/:filename",
    :ftp_servers => [
      {
        :host     => "sistema.dominio.com.ve",
        :user     => "usuario",
        :password => "clave"
      }
    ]
  }

Thanks in advance. (Gracias de antemano).

**Comment by boosty** [comment]
@cbagnoli Could you provide the full error message including a stack trace if possible?

Btw.: I hope that the credentials are not real. Please remember that this is a public page.

**Comment by boosty** [comment]
@cbagnoli Maybe this is the same problem this user was facing, which apparently got solved by using a higher timeout: https://github.com/xing/paperclip-storage-ftp/issues/32#issuecomment-154025964

**Comment by cbagnoli** [comment]
Thanks for yout reply and concern.

Credentials are user and password in Spanish, my native language. So, they are not real. And is not the same case.as mentioned in 32.

 I solved it modifying the gem. File:
   .rvm/gems/ruby-2.4.1/gems/paperclip-storage-ftp-1.2.7/lib/paperclip/storage/ftp/server.rb

Close to line 100, I replaced:
  list = connection.nlst(base)

By:
  begin
    list = connection.nlst(base)
  rescue => e
    list = []
  end

Apparently, the gem has problems rejecting from nil, on this line:
  tree.reject{|k,_| list.include?(k)}.each do |directory, sub_directories|

**Comment by cbagnoli** [comment]
Thanks for yout reply and concern.

Credentials are user and password in Spanish, my native language. So, they are not real. And is not the same case.as mentioned in 32.

I solved it modifying the gem. File:
.rvm/gems/ruby-2.4.1/gems/paperclip-storage-ftp-1.2.7/lib/paperclip/storage/ftp/server.rb

Close to line 100, I replaced:
list = connection.nlst(base)

By:
begin
list = connection.nlst(base)
rescue => e
list = []
end

Apparently, the gem has problems rejecting from nil, on this line:
tree.reject{|k,_| list.include?(k)}.each do |directory, sub_directories|

**Comment by boosty** [comment]
Hi @cbagnoli, sorry for the long delay.

I implemented a fix based on your suggestion: https://github.com/xing/paperclip-storage-ftp/pull/39

New gem version is 1.2.8. Please try it and let me know if it's working for you.
Thanks!
