### ISSUE TITLE
SFTP support?

### ISSUE THREAD

**Issue by hoahm** [xing/paperclip-storage-ftp#37]
In the sample code, I see you pass an array of ftp servers. So I want to ask:

1. Is it able to upload to both FTP servers at the same time? Or we can choose which FTP server we want to upload to?

2. I don't see you mention about SSL. Is it able to support SFTP?

````
    # The list of FTP servers to use
    :ftp_servers => [
      {
        :host     => "ftp1.example.com",
        :user     => "foo",
        :password => "bar"
      },
      # Add more servers if needed
      {
        :host     => "ftp2.example.com",
        :user     => "foo",
        :password => "bar",
        :port     => 2121, # optional, 21 by default
        :passive  => true  # optional, false by default
      }
    ]
````

**Comment by boosty** [comment]
Hi!

1. The gem will always upload to all specified servers in parallel.
2. SFTP is not supported by this gem, sorry.
